# Generated by Django 2.2.7 on 2019-12-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
