# Generated by Django 2.2.7 on 2019-12-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0002_auto_20191218_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='codigo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
